# Generated by Django 4.2.2 on 2023-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('c', 'Excellent')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
